<?php

namespace SueldoBundle\Repository;

/**
 * informesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class informesRepository extends \Doctrine\ORM\EntityRepository
{
}
