<?php

namespace SueldoBundle\Repository;

/**
 * periodosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class periodosRepository extends \Doctrine\ORM\EntityRepository
{
}
