<?php

namespace SueldoBundle\Repository;

/**
 * seuisaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class seuisaRepository extends \Doctrine\ORM\EntityRepository
{
}
