<?php

namespace SueldoBundle\Repository;

/**
 * sueafpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sueafpRepository extends \Doctrine\ORM\EntityRepository
{
}
