<?php

namespace SueldoBundle\Repository;

/**
 * suecargosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class suecargosRepository extends \Doctrine\ORM\EntityRepository
{
}
