<?php

namespace SueldoBundle\Repository;

/**
 * suedepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class suedepRepository extends \Doctrine\ORM\EntityRepository
{
}
