<?php

namespace SueldoBundle\Repository;

/**
 * sueiurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sueiurRepository extends \Doctrine\ORM\EntityRepository
{
}
