<?php

namespace SueldoBundle\Repository;

/**
 * sueparRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sueparRepository extends \Doctrine\ORM\EntityRepository
{
}
