<?php

namespace SueldoBundle\Repository;

/**
 * tabclaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tabclaRepository extends \Doctrine\ORM\EntityRepository
{
}
