<?php

namespace Amd\PiperBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CaractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaractRepository extends EntityRepository
{
}
