<?php

namespace Amd\PiperBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CtaespRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CtaespRepository extends EntityRepository
{
}
