<?php

namespace Amd\PiperBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PreimpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreimpRepository extends EntityRepository
{
}
